version: "3.7"
services:
    queue:
        image: rabbitmq:3.8-management
        ports:
          - "5672:5672"
          - "15672:15672"
    db:
        image: postgres:12.1
        restart: always
        environment:
          POSTGRES_PASSWORD: example